button_names = [
    ("var_people", "People"),
    ("var_animals", "Animals"),
    ("var_fantasy_creatures", "Fantasy Creatures"),
    ("var_skin", "Skin"),
    ("var_genitals", "Genitals"),
    ("var_sex", "Sex"),
    ("var_emotions", "Emotions"),
    ("var_eyes", "Eyes"),
    ("var_hair", "Hair"),
    ("var_clothing", "Clothing"),
    ("var_accessories", "Accessories"),
    ("var_objects", "Objects"),
    ("var_actions", "Actions"),
    ("var_places", "Places"),
    ("var_time_periods", "Time Periods"),
    ("var_times_of_day", "Times of Day"),
    ("var_mystical_elements", "Mystical Elements"),
    ("var_professions", "Professions"),
    ("var_weather", "Weather"),
    ("var_vehicles", "Vehicles"),
    ("var_food_drinks", "Food/Drinks"),
    ("var_nature_elements", "Nature Elements"),
    ("var_technology_tools", "Technology/Tools"),
    ("var_hobbies_activities", "Hobbies/Activities"),
    ("var_social_interactions", "Social Interactions"),
    ("var_legendary_places_realms", "Legendary Places/Realms"),
    ("var_historical_events_moments", "Historical Events/Moments"),
    ("var_body_language_gestures", "Body Language/Gestures"),
    ("var_art_styles", "Art Styles"),
    ("var_wildcards", "Wildcards"),
    ("var_custom_1", "Custom 1 (Camera Settings)"),
    ("var_custom_2", "Custom 2 (Lighting)"),
    ("var_custom_3", "Custom 3 (Image Detail)"),
]